---
version: '3.8'
services:
  pyapp1:
    build: ./pyapp1
    hostname: newapp1
    expose:
      - "8001"
  pyapp2:
    build: ./pyapp2
    hostname: newapp2
    expose:
      - "8002"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pyapp1
      - pyapp2
    ports:
      - "80:80"
networks:
  default:
    driver: bridge
    name: pynetwork
...
